### ISSUE TITLE
Question on running the predictor for inference.

### ISSUE THREAD

**Issue by JinyuanSun** [WangLabTHU/deepseed#1]
Great work, and it is nice to share codes with clean document! However, I tried to run `Predictor/promoter_predictor.py` for inference, but I got errors like:  
```
FileNotFoundError: [Errno 2] No such file or directory: '../case8_consituent/case8_constituent_seqsresults.csv'
```
Did I missed something? BTW, I trained the model ;).

Another minor issue occured during the training of the predictor:
```
The model type is : 
denselstm
/data4/promoter/deepseed/Predictor/SeqRegressionModel.py:701: UserWarning: nn.init.kaiming_normal is now deprecated in favor of nn.init.kaiming_normal_.
  nn.init.kaiming_normal(m.weight.data)
Training iters
  0%|                                                                                                                                                                       | 0/88 [00:00<?, ?it/s]Could not load symbol cublasGetSmCountTarget from libcublas.so.11. Error: /usr/local/cuda/lib64/libcublas.so.11: undefined symbol: cublasGetSmCountTarget
```
I can not run the training code with the version suggested in the README file (I use a RTX 3070 therefore I have to use cuda11). I am not sure will this be harmless or bad?
FYI, the training did converge:
```
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 11/11 [00:00<00:00, 39.14it/s]
epoch:32train_loss y:1.185442566871643 test_loss y:5.481445789337158 test_coefs:0.7354892771702892
EarlyStopping counter: 10 out of 10
```

Thanks!

**Comment by WangLabTHU** [comment]
Welcome to using DeepSEED. I think you are right, the right Env Requirements would be:
Python 3.7+.
PyTorch 1.7.1
CUDA 11.2 if you need train deep learning model with gpu.
I have updated the README file for accuracy. 

Additionally, I have uploaded the correct Predictor/promoter_predictor.py file for you to try out.
