### ISSUE TITLE
Constitutive mammalian promoter?

### ISSUE THREAD

**Issue by cnk113** [WangLabTHU/deepseed#2]
Hello,

I read your recent paper on DeepSEED, and I'm trying to use the tet-inducible design 11 from your paper which was quite leaky. I'm specifically requiring a constitutive/leaky tet-on system, and I was wondering if you had a leakier version than ones in the paper?

Best,
Chang

**Comment by WangLabTHU** [comment]
Hello, maybe you could contact zhangpc18@mails.tsinghua.edu.cn for the problem. He is the people in this research more familiar with experimental experience, maybe he have some solutions.
